source: ./
destination: ./_site
include:
  - ./README.md
  - ./CHANGELOG.md
  - ./resources/documentation/*
exclude:
  - "*.js"
  - "*.ts"
  - "*.json"
  - "*.mjs"
  - DOCUMENTATION.md
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme