source: ./
destination: ./_site
include:
  - ./CHANGELOG.md
  - ./resources/documentation/*
  - ./docs/*
exclude:
  - "*.js"
  - "*.ts"
  - "*.json"
  - "*.mjs"
  - "*.map"
  - node_modules/
  - _site/
  - DOCUMENTATION.md
  - README.md
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme